### ISSUE TITLE
Ajouter le Siret/lien vers registre entreprises

### ISSUE THREAD

**Issue by thom4parisot** [dtc-innovation/dtc-innovation.github.io#17]
Équivalent anglais : Companies House.

**Comment by DavidBruant** [comment]
Pourquoi ? Les gens peuvent le trouver sur societe.com ou nous le demander.
Je ne comprends pas l'importance de le mettre sur le site. Ca ne ressemble pas non plus à une pratique commune des sites d'entreprise

**Comment by DavidBruant** [comment]
Ca fait très administratif upfront, je trouve

**Comment by thom4parisot** [comment]
C'était pour l'avoir sous le coude sans avoir à créer une page _mentions légales_.
Et par praticité pour le trouver quelque part sans avoir à chercher sur les Internets.

**Comment by DavidBruant** [comment]
> C'était pour l'avoir sous le coude sans avoir à créer une page mentions légales.

Sous le coude pour nous (dtc) ?

**Comment by thom4parisot** [comment]
Oui – je ne sais pas si c'est le genre de détail qui sert à d'autres organismes mais si c'était le cas, on en revient à la page _mentions légales_.

**Comment by thom4parisot** [comment]
Remplacé par #21
