### ISSUE TITLE
Hover effect on DTC title

### ISSUE THREAD

**Issue by DirtyF** [dtc-innovation/dtc-innovation.github.io#44]
![dtc-hover](https://user-images.githubusercontent.com/103008/33073890-8e1f1818-cec4-11e7-9c97-d03ae4540e8a.png)

1. Useless on the homepage
2. Strikes the baseline on hover
3. Redundant with the `home` navigation menu item

The color effect is nice but you don't need the underline text-decoration. 
I'll happily submit a PR if you agree.

**Comment by thom4parisot** [comment]
Hi @DirtyF!

It's a good idea for the homepage.

What about the other pages? The title link hovering will still be problematic.
We could totally use a different decoration too. What do you think?

**Comment by DirtyF** [comment]
Sure, you could do with whatever effect suits you the most (animation scale, accessible random color like you did in your reveal theme, etc.) on all pages

**Comment by thom4parisot** [comment]
Be my guest 🙂
