### ISSUE TITLE
Stick the word "webloki" somewhere?

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/dtc-innovation.github.io#9]
https://twitter.com/naholyr/status/830762608911347712

**Comment by thom4parisot** [comment]
Do we need to explain a new concept rather than acknowledging they are simply web pages based carrying different intent?

Looks like it is imposing on the user the need to explain technical details during a totally different reading experience.

**Comment by DavidBruant** [comment]
This issue was more a joke than anything else ;-)
